- action:
  - service: persistent_notification.create
  alias: BBC Breaking News
  condition: []
  id: '1517264039199'
  trigger:
  - platform: mqtt
    topic: bbc_news/breaking
- action:
  - service: script.1517281436557
  alias: Rowan's Lights Out - School Night
  condition:
  - condition: state
    entity_id: input_boolean.is_school_day
    state: 'on'
  id: '1517279821891'
  trigger:
  - at: '19:50:00'
    platform: time
- action:
  - service: script.1517281436557
  alias: Rowan's Lights Out - Weekend
  condition:
  - condition: state
    entity_id: input_boolean.is_school_day
    state: 'off'
  id: '1517284692661'
  trigger:
  - at: '20:50:00'
    platform: time
- action:
  - data:
      entity_id: switch.lava_lamp
    service: switch.turn_off
  alias: Turn Lava Lamp Off (night)
  condition: []
  id: '1517285524856'
  trigger:
  - at: 00:00:00
    platform: time
- action:
  - data:
      entity_id: switch.lava_lamp
    service: switch.turn_on
  alias: Turn Rowan's Lava Lamp On (morning)
  condition: []
  id: '1517286288982'
  trigger:
  - at: 05:00:00
    platform: time
- action:
  - data:
      entity_id: switch.lava_lamp
    service: switch.turn_on
  alias: Turn Rowan's Lava Lamp On (night)
  condition: []
  id: '1517286593693'
  trigger:
  - at: '12:00:00'
    platform: time
- action:
  - data:
      entity_id: switch.scooter
    service: switch.turn_off
  alias: Turn the scooter off at 04:00
  condition: []
  id: '1517289206005'
  trigger:
  - at: 04:00:00
    platform: time
- action:
  - data:
      entity_id: switch.scooter
    service: switch.turn_on
  alias: Turn the scooter on at 22:00
  condition: []
  id: '1517289270869'
  trigger:
  - at: '22:00:00'
    platform: time

