homeassistant:
  name: Home
  latitude:    !secret home_lat
  longitude:   !secret home_lon
  elevation:   67
  unit_system: metric
  time_zone:   Europe/London
  customize:   !include customize.yaml

frontend:
config:
http:
  # api_password: !secret http_password
  # base_url: example.duckdns.org:8123

updater:
  include_used_components: true

discovery:
conversation:

history:
logbook:
map:
cloud:
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
recorder:
