homeassistant:
  name: Home
  latitude:    !secret home_lat
  longitude:   !secret home_lon
  elevation:   67
  unit_system: metric
  time_zone:   Europe/London
  customize:   !include customize.yaml

frontend:
  themes:            !include_dir_named themes/
config:

http:
#  api_password: !secret http_api_password
#  ip_ban_enabled: True
#  login_attempts_threshold: 5
#  server_host: !secret http_server_host
#  server_port: !secret http_server_port
#  base_url: !secret http_base_url
#  cors_allowed_origins:
#      - https://google.com
#      - https://home-assistant.io
#      - !secret http_base_url
#    use_x_forwarded_for: True
#    trusted_networks:
#      - 127.0.0.1
#      - ::1
#      - 192.168.0.0/24



updater:
  include_used_components: true

discovery:
conversation:

history:
logbook:
map:
cloud:
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
recorder:

mqtt: !include mqtt.yaml
weblink: !include weblinks.yaml
zone: !include_dir_list zones/
ifttt: !include ifttt.yaml
duckdns: !include duckdns.yaml
shopping_list:
sun:
light: !include_dir_list lights/
switch:              !include_dir_list switches/
sensor:              !include_dir_list sensor/
#android_ip_webcam:   !include_dir_list android_ip_webcam/
binary_sensor:       !include_dir_list binary_sensor/
#camera:              !include_dir_list cameras/
device_tracker:      !include_dir_list device_tracker/
logger:
  default: error
  logs:
    homeassistant.components.camera: critical
    homeassistant.components.broadlink: critical

input_boolean:       !include_dir_merge_named input_booleans/
input_number:        !include_dir_merge_named input_numbers/
input_select:        !include_dir_merge_named input_selects/
panel_iframe:        !include_dir_merge_named panel_iframes/
alarm_control_panel: !include_dir_list alarm_control_panel/
history_graph:       !include_dir_named history_graphs/
media_player:        !include_dir_list media_players/
notify:              !include_dir_list notify/
joaoapps_join:       !include joaoapps_join.yaml
tts:                 !include_dir_list tts_providers/
